### ISSUE TITLE
Writing checklist

### ISSUE THREAD

**Issue by katyhuff** [andrewryh/MScThesis-MSBR#2]
- [ ] Articles such as "a" "the" "some" "any" and "each" appear where necessary.
- [ ] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty")
- [ ] Avoid run-on sentences.
- [ ] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [ ] reduce vague words (important, methodologic)
- [ ] reduce acronyms / jargon
- [ ] get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [ ] get rid of extraneous adverbs (very, really, quite, basically, generally)
- [ ] get rid of there are / there is
- [ ] turn negatives to positives (she was not often right -> she was usually wrong)
- [ ] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [ ] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [ ] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [ ] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes") 
- [ ] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [ ] data is plural (the data are critical)
- [ ] compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [ ] punctuation helps you to vary your sentence structure
- [ ] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [ ] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [ ] semicolon: connects two independent clauses. OR used to separate when the items in the list contain internal punctuation.
- [ ] use a colon to introduce a list, quote, explanation, conclusion, or amplification
- [ ] if there's a list in a sentence, it shouldn't come before the colon
- [ ] use a dash to insert something in the middle of the sentence. Don't overuse it.
